### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Fixes https://github.com/bmc/classutil/issues/24

### CODE REVIEW

**Comment by bmc** [comment]
Thanks. I want to run a few tests, but this looks good (and Travis CI likes it). I'll roll it into a new version shortly.

**Comment by ElfoLiNk** [comment]
Thanks, please check the sbt-bintray plugin if it's still working due to the sbt 1.0 upgrade

**Comment by bmc** [comment]
This PR now has conflicts, because another one sneaked in ahead of it. I'll address the conflicts and then merge, probably this evening.

**Comment by SethTisue** [comment]
many of these changes are in my PR, but a couple weren't. the additional changes look good to me.

**Pull request merged**
