### PR TITLE
Add info about the runtime annotations of a class

### PR DESCRIPTION
**Pull request by ruippeixotog**
Fixes issue #17 that I created previously.

### CODE REVIEW

**Comment by rcsenkbeil** [comment]
Is there any intent to merge this in? Would be really nice to see made available.

**Comment by bmc** [comment]
> On Jul 16, 2015, at 3:31 PM, Chip Senkbeil <notifications@github.com> wrote:
> 
> Is there any intent to merge this in? Would be really nice to see made available.
> 
There is. Just haven’t gotten to it, because I’ve been traveling like crazy.

**Comment by ruippeixotog** [comment]
Hi @bmc! Is this project permanently abandoned? If not, it would be great to see this merged :) Right now I have to maintain a fork just with this change for projects that depend on this...

**Comment by bmc** [comment]
Sorry, no. It's not abandoned. Merging it now. Look for a new release shortly.

**Comment by bmc** [comment]
Pushing release 1.0.6 shortly.

**Comment by bmc** [comment]
Just tagged, pushed, and published version 1.0.6, which contains this fix. Might take a bit until it shows up in Maven Central, but it should be in JCenter now.

**Comment by ruippeixotog** [comment]
Wow, thanks for the quick action! :)

**Comment by bmc** [comment]
Only took me a year... Sorry for the delay.

**Pull request merged**
